spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seluneadminout.mysql.rds.aliyuncs.com:3306/luckymoney?characterEncoding=utf-8&useSSL=false
    username: root
    password: XYP@1224susu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true